In [1]:
import pandas as pd
import re

In [2]:
file_path = "newscraper/newscraper/complete_scrape.json"
df = pd.read_json(file_path)
df.head()

,headline,desc,url,published_datetime,category,year,month,day
0,Lankans score 333 in warm-up game against India,Sri Lanka scored 333/5 in 50 overs againstIndi...,https://www.adaderana.lk/sportsnews.php?nid=5874,"| June 1, 2013 7:05 pm",Sports,2013,June,1
1,Trinity beat Royal in Bradby 1st leg,Trinity beat Royal College 37-25 in the 1st le...,https://www.adaderana.lk/sportsnews.php?nid=5875,"| June 1, 2013 7:07 pm",Sports,2013,June,1
2,India beat Sri Lanka by five wickets in warm u...,Virat Kohli and Dinesh Karthik both scored cen...,https://www.adaderana.lk/sportsnews.php?nid=5876,"| June 1, 2013 11:29 pm",Sports,2013,June,1
3,Conference on Digital Public Infrastructure…,"The High Commission of India, in partnership w...",https://www.adaderana.lk/news.php?mode=head&ni...,"| March 26, 2024",Top News Story 2,2024,March,26
4,Point Pedro hospital’s new Accident & Emergenc...,President Ranil Wickremesinghe on Friday (Marc...,https://www.adaderana.lk/news.php?mode=head&ni...,"| March 23, 2024",Top News Story 2,2024,March,23

In [3]:
df.shape

(115928, 8)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115928 entries, 0 to 115927
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   headline            115927 non-null  object
 1   desc                115928 non-null  object
 2   url                 115928 non-null  object
 3   published_datetime  115926 non-null  object
 4   category            115928 non-null  object
 5   year                115928 non-null  int64
 6   month               115928 non-null  object
 7   day                 115928 non-null  int64
dtypes: int64(2), object(6)
memory usage: 7.1+ MB

In [5]:
df.duplicated().sum()

np.int64(318)

In [6]:
df[df.duplicated()].head(10)

,headline,desc,url,published_datetime,category,year,month,day
82724,"Tamil refugee, seeks Aussie Senate seat","As an ex-banker of Tamil heritage, Brami Jegan...",https://www.adaderana.lk/news.php?nid=8960,"| July 14, 2010 7:25 am",Breaking News,2010,July,14
82725,26hr water cut for part of Colombo,There will be a 26 hour water cut to the Colom...,https://www.adaderana.lk/news.php?nid=8961,"| July 14, 2010 9:58 am",Breaking News,2010,July,14
82726,Kilinochchi cabinet meeting underway,The first cabinet meeting in Sri Lanka’s forme...,https://www.adaderana.lk/news.php?nid=8962,"| July 14, 2010 10:24 am",Breaking News,2010,July,14
82727,"Buhne recall, UNDP closure, UN fallacy?",The Associate spokesman for the UN Secretary-G...,https://www.adaderana.lk/news.php?nid=8963,"| July 14, 2010 12:05 pm",Breaking News,2010,July,14
82728,"Believes party needs a change in leadership, s...",While accepting the present leadership of the ...,https://www.adaderana.lk/news.php?nid=8964,"| July 14, 2010 1:21 pm",Breaking News,2010,July,14
82729,Fuel prices down in Jaffna,Fuel prices have been reduced in the Jaffna wi...,https://www.adaderana.lk/news.php?nid=8965,"| July 14, 2010 3:22 pm",Breaking News,2010,July,14
82730,"Vaiko, Nedumaran arrested by Chennai police",Several persons including P. Nedumaran and Vai...,https://www.adaderana.lk/news.php?nid=8966,"| July 14, 2010 4:11 pm",Breaking News,2010,July,14
82731,Police to go green,The Sri Lanka Police is to set up units under ...,https://www.adaderana.lk/news.php?nid=8967,"| July 14, 2010 5:26 pm",Breaking News,2010,July,14
82732,Mattakkuliya incident: 23 identified by witnesses,After a marathon identification parade held ov...,https://www.adaderana.lk/news.php?nid=8968,"| July 14, 2010 5:44 pm",Breaking News,2010,July,14
82733,Four bodies from one family found in Eppawala ...,Four bodies have been recovered from a house a...,https://www.adaderana.lk/news.php?nid=8969,"| July 14, 2010 5:59 pm",Breaking News,2010,July,14

In [7]:
df[df['headline']== 'Tamil refugee, seeks Aussie Senate seat']

,headline,desc,url,published_datetime,category,year,month,day
82406,"Tamil refugee, seeks Aussie Senate seat","As an ex-banker of Tamil heritage, Brami Jegan...",https://www.adaderana.lk/news.php?nid=8960,"| July 14, 2010 7:25 am",Breaking News,2010,July,14
82724,"Tamil refugee, seeks Aussie Senate seat","As an ex-banker of Tamil heritage, Brami Jegan...",https://www.adaderana.lk/news.php?nid=8960,"| July 14, 2010 7:25 am",Breaking News,2010,July,14

published_datetime column has two formats of data - one with date and time as well as one with just the date

In [8]:
df  = df.drop_duplicates()
df.shape

(115610, 8)

In [9]:
df.published_datetime

0            | June 1, 2013  7:05 pm
1            | June 1, 2013  7:07 pm
2           | June 1, 2013  11:29 pm
3                   | March 26, 2024
4                   | March 23, 2024
                     ...
115923     | March 17, 2020  7:58 pm
115924     | March 17, 2020  8:14 pm
115925     | March 17, 2020  9:40 pm
115926    | March 17, 2020  10:43 pm
115927    | March 17, 2020  11:30 pm
Name: published_datetime, Length: 115610, dtype: object

In [10]:
df.isnull().sum()

headline              1
desc                  0
url                   0
published_datetime    2
category              0
year                  0
month                 0
day                   0
dtype: int64

In [11]:
df[df['headline'].isnull()==True]

,headline,desc,url,published_datetime,category,year,month,day
109303,None,,https://www.adaderana.lk/news.php?nid=7996,"| October 17, 2010 12:33 pm",Breaking News,2010,October,17

In [12]:
df[df['headline'].isnull()==True].index

Index([109303], dtype='int64')

In [13]:
df = df.drop(df[df['headline'].isnull()==True].index, axis=0)

In [14]:
df[df['published_datetime'].isnull()==True]

,headline,desc,url,published_datetime,category,year,month,day
2890,Fallon crowned....,22 year old Fallon Ransinghe was crowed Derana...,https://www.adaderana.lk/news.php?mode=head&ni...,None,Top News Story 1,2010,August,14
82336,World Env. Day: Bulathsinhala Shramadana campa...,"In line with World Environment Day, a clean-up...",https://www.adaderana.lk/news.php?nid=41115,None,Breaking News,2017,June,5

In [15]:
df.isnull().sum()

headline              0
desc                  0
url                   0
published_datetime    2
category              0
year                  0
month                 0
day                   0
dtype: int64

In [16]:
def extract_time(text: object):
    text = str(text)
    regx = re.compile(r"\b(?P<time>(?:[1-9]|1[0-2]):[0-5]\d\s(?:am|pm))\b")
    data = regx.search(text)
    return data.group('time') if data else None

In [17]:
df['published_time'] = df['published_datetime'].apply(extract_time)
df.head()

,headline,desc,url,published_datetime,category,year,month,day,published_time
0,Lankans score 333 in warm-up game against India,Sri Lanka scored 333/5 in 50 overs againstIndi...,https://www.adaderana.lk/sportsnews.php?nid=5874,"| June 1, 2013 7:05 pm",Sports,2013,June,1,7:05 pm
1,Trinity beat Royal in Bradby 1st leg,Trinity beat Royal College 37-25 in the 1st le...,https://www.adaderana.lk/sportsnews.php?nid=5875,"| June 1, 2013 7:07 pm",Sports,2013,June,1,7:07 pm
2,India beat Sri Lanka by five wickets in warm u...,Virat Kohli and Dinesh Karthik both scored cen...,https://www.adaderana.lk/sportsnews.php?nid=5876,"| June 1, 2013 11:29 pm",Sports,2013,June,1,11:29 pm
3,Conference on Digital Public Infrastructure…,"The High Commission of India, in partnership w...",https://www.adaderana.lk/news.php?mode=head&ni...,"| March 26, 2024",Top News Story 2,2024,March,26,None
4,Point Pedro hospital’s new Accident & Emergenc...,President Ranil Wickremesinghe on Friday (Marc...,https://www.adaderana.lk/news.php?mode=head&ni...,"| March 23, 2024",Top News Story 2,2024,March,23,None

In [18]:
df = df.drop(columns=['published_datetime'])
df

,headline,desc,url,category,year,month,day,published_time
0,Lankans score 333 in warm-up game against India,Sri Lanka scored 333/5 in 50 overs againstIndi...,https://www.adaderana.lk/sportsnews.php?nid=5874,Sports,2013,June,1,7:05 pm
1,Trinity beat Royal in Bradby 1st leg,Trinity beat Royal College 37-25 in the 1st le...,https://www.adaderana.lk/sportsnews.php?nid=5875,Sports,2013,June,1,7:07 pm
2,India beat Sri Lanka by five wickets in warm u...,Virat Kohli and Dinesh Karthik both scored cen...,https://www.adaderana.lk/sportsnews.php?nid=5876,Sports,2013,June,1,11:29 pm
3,Conference on Digital Public Infrastructure…,"The High Commission of India, in partnership w...",https://www.adaderana.lk/news.php?mode=head&ni...,Top News Story 2,2024,March,26,None
4,Point Pedro hospital’s new Accident & Emergenc...,President Ranil Wickremesinghe on Friday (Marc...,https://www.adaderana.lk/news.php?mode=head&ni...,Top News Story 2,2024,March,23,None
...,...,...,...,...,...,...,...,...
115923,Number of coronavirus patients in Sri Lanka su...,Nine more persons have tested positive for cor...,https://www.adaderana.lk/news.php?nid=61469,Covid-19,2020,March,17,7:58 pm
115924,"Public not to visit local historical, archaeol...","Ministry of Buddha Sasana, Cultural and Religi...",https://www.adaderana.lk/news.php?nid=61471,Covid-19,2020,March,17,8:14 pm
115925,President announces relief measures for people...,A maximum retail price of Rs 65 for 1-kilo dha...,https://www.adaderana.lk/news.php?nid=61474,Covid-19,2020,March,17,9:40 pm
115926,President wants ad-hoc actions of govt. agenci...,President Gotabaya Rajapaksa has directed that...,https://www.adaderana.lk/news.php?nid=61476,Covid-19,2020,March,17,10:43 pm
115927,Visa extended for foreigners currently in country,Due to the spread of the Covid-19 virus in the...,https://www.adaderana.lk/news.php?nid=61479,Covid-19,2020,March,17,11:30 pm

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115609 entries, 0 to 115927
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   headline        115609 non-null  object
 1   desc            115609 non-null  object
 2   url             115609 non-null  object
 3   category        115609 non-null  object
 4   year            115609 non-null  int64
 5   month           115609 non-null  object
 6   day             115609 non-null  int64
 7   published_time  112513 non-null  object
dtypes: int64(2), object(6)
memory usage: 7.9+ MB

In [20]:
df.to_csv('adaderana_complete_news_archive.csv')